version: 0.1
phases:
  install:
    commands:
      - echo "Installing MKDocs Requirements"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building Website"
      - mkdocs build
  post_build:
    commands:
      - aws s3 sync ./site s3://dhruvthukral.com --acl public-read --exclude "*.py" --exclude "*.pyc" --cache-control "public, max-age=86400"
