site_name: Dhruv Thukral

pages: 
  - Home: index.md
  - Resume: resume.md
  - Publications: publications.md
  - Patents: patents.md
  - Presentations: presentations.md

theme: cinder

site_author: Dhruv Thukral

site_favicon: favicon.ico
